### ISSUE TITLE
How can l monitor the network via Android 12?

### ISSUE THREAD

**Issue by qlenlen** [sorakadoaoR/sportCampusSignHelper#1]

**Comment by sorakadoaoR** [comment]
You can try an app called HttpCanary. If that don't work, then you may need to use a computer a capture network traffic.

**Comment by qlenlen** [comment]
I run Httpcanary at a rooted device with the system ca, but it does not work. App shows "error network".

**Comment by qlenlen** [comment]
Thanks. HttpCanary with TrustMeAlready make it  avaiable.
