### ISSUE TITLE
刷一次会实际完成两次？

### ISSUE THREAD

**Issue by dongfengruhua** [sorakadoaoR/sportCampusSignHelper#6]
### 问题阐述
我学校限制一天一刷，试用后发现会完成两次
### 预期的效果
刷一次只有一次

### 实际的效果
**刷一次会有两次，并且点开历史记录也只有一次，却显示两次**
终端如下
> 登录成功
可签到时间段"[[\"09:00\",\"22:00\"],[\"\",\"\"],[\"\",\"\"],[\"\",\"\"],[\"\",\"\"]]"
输入 y+回车 继续签到，输入其他退出: y
{'msg': '本次签到成功', 'code': 200}
>

但app显示是完成了两次，（这是我毕业朋友的号，刷之前是零次）

![90883c5a71a04032f906a4a6eac67811](https://github.com/sorakadoaoR/sportCampusSignHelper/assets/127479032/8abc786d-dd27-44db-97de-f91611acb3ff)

> 还好用的已经的毕业朋友的号，不然多少出点问题

**Comment by sorakadoaoR** [comment]
我这边有几个人在用，没出现过这个问题。程序是只会发送一次签到请求的，多出来一次只能说高校体育那边的数据库一致性没做好。你可以多用几次试试，看是不是会稳定出现这个问题

**Comment by dongfengruhua** [comment]
> 我这边有几个人在用，没出现过这个问题。程序是只会发送一次签到请求的，多出来一次只能说高校体育那边的数据库一致性没做好。你可以多用几次试试，看是不是会稳定出现这个问题

之后就正常了，感谢您的开源程序！
